title: Git Test
author: GitHub User1
email: my-email@domain.com
theme: minima
description: > # Modify the description for the file

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
